sudo: required
notifications:
  email: false

script:
- dpkg-buildpackage -us -uc -b

install:
- sudo apt update && sudo apt install -yq rsync golang-go binutils dpkg-dev build-essential fakeroot debhelper

