sudo: required
language: go
notifications:
  email: false

go:
  - "1.10.x"

script:
- dpkg-buildpackage -us -uc -b

install:
- sudo apt update && sudo apt install -yq rsync golang-go binutils dpkg-dev build-essential fakeroot debhelper

